server:
  port: 8189
  servlet:
    context-path: /telros
spring:
  datasource:
    url: jdbc:h2:file:./users;MODE=PostgreSQL
    #url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        #ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2

# Launch the default browser when starting the application in development mode
#vaadin:
#  launch-browser: true